sonar.projectKey=samiwadhies_8.2CDevSecOps
sonar.organization=samiwadhies
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.exclusions=node_modules/**,test/**,sonar-scanner-*/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
